version: '3'

services:
  db:
    image: postgres:alpine
    container_name: shipping-db
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "mydb"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5555:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB' ]
      interval: 1s
      timeout: 1s
      retries: 15

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shipping-app
    ports:
      - '8888:8080'
    volumes:
      - ./src:/app/src
    depends_on:
      - db

volumes:
    pgdata:
